version: "3.7"

services:
  init-genesis:
    hostname: init-genesis
    env_file:
      - .env
    image: ethereum/client-go:alltools-v1.13.10
    command: geth init --datadir root/.ethereum/dchain genesis/genesis.json
    volumes:
      - ${PATH_DCHAIN}/genesis:/genesis
      - ${PATH_DCHAIN}/dchain:/root/.ethereum/dchain

  geth-non-authority:
    hostname: geth-non-authority
    env_file:
      - .env
    image: geth-non-authority
    depends_on:
      init-genesis:
        condition: service_completed_successfully
    build:
      context: .
    command: --datadir root/.ethereum/dchain
      --bootnodes ${BOOTNODE_ENODE}
      --syncmode "full"
      --gcmode archive
      --networkid=${NETWORK_ID}
      --discovery.port 30305
      --port 30305
      --http
      --http.addr="0.0.0.0"
      --http.api="eth,web3,net,clique"
      --http.vhosts "0.0.0.0"
      --http.port 8545
      --http.corsdomain="*"
      --ethstats ${ETH_STATS}
      --maxpeers 100
      --cache 1024
    ports:
      - "8545:8545"
      - "30305:30305"
    volumes:
      - ${PATH_DCHAIN}/dchain:/root/.ethereum/dchain
    networks:
      priv-eth-net:

networks:
  priv-eth-net:
    driver: bridge
    name: priv-eth-net
